# Generated by Django 4.2 on 2023-09-19 08:22

import core.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('file', models.FileField(blank=True, default='', upload_to=core.utils.get_document_filename)),
                ('filename', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, default='', upload_to=core.utils.get_image_filename)),
                ('map', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Navigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seqno', models.PositiveIntegerField(blank=True, default=0)),
                ('label', models.CharField(max_length=32)),
                ('type', models.IntegerField(choices=[(1, 'URL'), (2, 'Content page'), (3, 'List/Search shows'), (4, 'Schedule'), (5, 'List venues'), (8, 'Donations'), (6, 'Archive index'), (7, 'Archive home')])),
                ('url', models.URLField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ('festival', 'seqno', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=64)),
                ('body', models.TextField(blank=True, default='')),
                ('body_test', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, default='', upload_to=core.utils.get_image_filename)),
            ],
            options={
                'ordering': ('page', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('text/css', 'CSS stylesheet'), ('text/html', 'HTML template'), ('application/javascript', 'Javascript')], max_length=64)),
                ('body', models.TextField(blank=True, default='')),
                ('body_test', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
    ]
