# Generated by Django 2.1.3 on 2018-11-23 17:00

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_auto_20181122_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seqno', models.PositiveIntegerField(blank=True, default=0)),
                ('label', models.CharField(max_length=32)),
                ('type', models.IntegerField(choices=[(1, 'URL'), (2, 'Content page'), (3, 'List/search shows'), (4, 'Schedule'), (5, 'List venues')])),
                ('url', models.URLField(blank=True, default='', max_length=32)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigators', to='core.Festival')),
            ],
            options={
                'ordering': ('festival', 'seqno', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=64)),
                ('body', models.TextField(blank=True, default='')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.Festival')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, default='', upload_to=core.utils.get_image_filename)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.Page')),
            ],
            options={
                'ordering': ('page', 'name'),
            },
        ),
        migrations.AddField(
            model_name='navigator',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='navigators', to='content.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='pageimage',
            unique_together={('page', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('festival', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='navigator',
            unique_together={('festival', 'label')},
        ),
    ]
