# Generated by Django 2.1.5 on 2019-02-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigator',
            name='url',
            field=models.URLField(blank=True, default='', max_length=256),
        ),
    ]
