# Generated by Django 4.2 on 2023-09-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.festival'),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.festival'),
        ),
        migrations.AddField(
            model_name='navigator',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigators', to='core.festival'),
        ),
        migrations.AddField(
            model_name='navigator',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='navigators', to='content.page'),
        ),
        migrations.AddField(
            model_name='image',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.festival'),
        ),
        migrations.AddField(
            model_name='document',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.festival'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('festival', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pageimage',
            unique_together={('page', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('festival', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='navigator',
            unique_together={('festival', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('festival', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('festival', 'name')},
        ),
    ]
