# Generated by Django 2.1.5 on 2019-02-17 09:21

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_festival_is_archived'),
        ('content', '0002_auto_20190216_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('file', models.FileField(blank=True, default='', upload_to=core.utils.get_document_filename)),
                ('file_name', models.CharField(blank=True, default='', max_length=64)),
                ('mime_type', models.CharField(blank=True, default='', max_length=64)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.Festival')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, default='', upload_to=core.utils.get_image_filename)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.Festival')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('festival', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('festival', 'name')},
        ),
    ]
