# Generated by Django 5.0.9 on 2025-05-02 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('core', '0003_add_previous_festival'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigator',
            options={'ordering': ('festival', 'parent_id', 'seqno', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='navigator',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='navigator',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.navigator'),
        ),
        migrations.AlterField(
            model_name='navigator',
            name='type',
            field=models.IntegerField(choices=[(0, 'Menu'), (1, 'URL'), (2, 'Content page'), (3, 'List/Search shows'), (4, 'Schedule'), (5, 'List venues'), (8, 'Donations'), (6, 'Archive index'), (7, 'Archive home')]),
        ),
        migrations.AlterUniqueTogether(
            name='navigator',
            unique_together={('festival', 'parent', 'label')},
        ),
    ]
