# Generated by Django 5.0.9 on 2025-05-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_nested_navigators'),
        ('core', '0003_add_previous_festival'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='navigator',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pageimage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='navigator',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.navigator'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('festival', 'name'), name='unique_document_name'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('festival', 'name'), name='unique_image_name'),
        ),
        migrations.AddConstraint(
            model_name='navigator',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('festival', 'label'), name='unique_root_navigator_label'),
        ),
        migrations.AddConstraint(
            model_name='navigator',
            constraint=models.UniqueConstraint(fields=('festival', 'parent', 'label'), name='unique_navigator_item_label'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('festival', 'name'), name='unique_page_name'),
        ),
        migrations.AddConstraint(
            model_name='pageimage',
            constraint=models.UniqueConstraint(fields=('page', 'name'), name='unique_page_image_name'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('festival', 'name'), name='unique_resource_name'),
        ),
    ]
