# Generated by Django 2.1.5 on 2019-02-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_page_body_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_name',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='document',
            name='mime_type',
        ),
    ]
