# Generated by Django 2.1.5 on 2019-02-20 11:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_festival_is_archived'),
        ('content', '0005_auto_20190217_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('body', models.TextField(blank=True, default='')),
                ('body_test', models.TextField(blank=True, default='')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.Festival')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('festival', 'name')},
        ),
    ]
