# Generated by Django 2.1.5 on 2019-02-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20190220_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('text/css', 'CSS stylesheet'), ('application/javascript', 'Javascript')], default='text/css', max_length=64),
            preserve_default=False,
        ),
    ]
