# Generated by Django 2.2 on 2019-04-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigator',
            name='type',
            field=models.IntegerField(choices=[(1, 'URL'), (2, 'Content page'), (3, 'List/search shows'), (4, 'Schedule'), (5, 'List venues'), (6, 'Archive index'), (7, 'Archive home')]),
        ),
    ]
