# Generated by Django 3.2.3 on 2021-06-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20190427_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigator',
            name='type',
            field=models.IntegerField(choices=[(1, 'URL'), (2, 'Content page'), (3, 'List/Search shows'), (4, 'Schedule'), (5, 'List venues'), (8, 'Donations'), (6, 'Archive index'), (7, 'Archive home')]),
        ),
    ]
