# Generated by Django 4.0.5 on 2023-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_navigator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('text/css', 'CSS stylesheet'), ('text/html', 'HTML template'), ('application/javascript', 'Javascript')], max_length=64),
        ),
    ]
