# Generated by Django 4.0.5 on 2023-02-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='map',
            field=models.TextField(blank=True, default=''),
        ),
    ]
