# Generated by Django 2.1.1 on 2018-09-23 12:12

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, default='', upload_to=core.utils.get_image_filename)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='festival.ContentPage')),
            ],
            options={
                'ordering': ('page', 'name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='contentpageimage',
            unique_together={('page', 'name')},
        ),
    ]
