# Generated by Django 2.1.3 on 2018-11-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_auto_20180923_1312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentpage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='festival',
        ),
        migrations.AlterUniqueTogether(
            name='contentpageimage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contentpageimage',
            name='page',
        ),
        migrations.AlterUniqueTogether(
            name='navigatoroption',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='navigatoroption',
            name='festival',
        ),
        migrations.RemoveField(
            model_name='navigatoroption',
            name='page',
        ),
        migrations.DeleteModel(
            name='ContentPage',
        ),
        migrations.DeleteModel(
            name='ContentPageImage',
        ),
        migrations.DeleteModel(
            name='NavigatorOption',
        ),
    ]
