# Generated by Django 4.2 on 2023-09-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tickets', '0005_add_fringertypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='fringer_price',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='fringer_shows',
        ),
    ]
