# Generated by Django 2.1.1 on 2018-09-19 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='festival',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='site',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='festival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='festival', to='core.Festival'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='sites.Site'),
        ),
    ]
