# Generated by Django 2.1.1 on 2018-09-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180919_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='festival', to='core.Festival'),
        ),
    ]
