# Generated by Django 5.0.9 on 2024-11-23 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_online_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.festival'),
        ),
    ]
