# Generated by Django 5.0.14 on 2026-03-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_previous_festival'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
