# Generated by Django 2.1.1 on 2018-09-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180919_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='base_template',
            field=models.CharField(default='tf_base.html', max_length=64),
            preserve_default=False,
        ),
    ]
