# Generated by Django 5.0.14 on 2026-03-14 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_festival_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dbs',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL('update core_user cu set is_dbs = vv.is_dbs from volunteers_volunteer vv where vv.user_id = cu.id', reverse_sql=''),
        migrations.AddField(
            model_name='user',
            name='volunteer_roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='volunteers.role'),
        ),
        migrations.RunSQL('insert into core_user_volunteer_roles (user_id, role_id) select volunteer_id, role_id from volunteers_volunteer_roles', reverse_sql=''),
        migrations.AlterField(
            model_name='festival',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.festival'),
        ),
    ]
