# Generated by Django 2.1.1 on 2018-09-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteinfo_base_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='base_template',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='footer',
            field=models.CharField(default='site/theatrefest/footer.html', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='header',
            field=models.CharField(default='site/theatrefest/header.html', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='navigator',
            field=models.CharField(default='site/theatrefest/navigator.html', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='stylesheet',
            field=models.CharField(default='site/theatrefest/styles.css', max_length=64),
            preserve_default=False,
        ),
    ]
