# Generated by Django 2.1.1 on 2018-09-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180919_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='banner',
            field=models.CharField(default='site/theatrefest/banner.html', max_length=64),
            preserve_default=False,
        ),
    ]
