# Generated by Django 2.1.1 on 2018-09-19 20:37

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteinfo_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='banner',
            field=models.ImageField(blank=True, default='', upload_to=core.utils.get_image_filename),
        ),
        migrations.AddField(
            model_name='festival',
            name='venue_map',
            field=models.ImageField(blank=True, default='', upload_to=core.utils.get_image_filename),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='banner',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='footer',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='header',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='navigator',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='stylesheet',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
