# Generated by Django 2.1.1 on 2018-09-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0007_auto_20180919_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['site', 'festival', 'email']},
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Users', to='sites.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('site', 'festival', 'email')},
        ),
    ]
