# Generated by Django 2.1.1 on 2018-09-22 10:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180920_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=64)),
                ('body', models.TextField(blank=True, default='')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pages', to='core.Festival')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.CreateModel(
            name='NavigatorOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seqno', models.PositiveIntegerField(blank=True, default=0)),
                ('label', models.CharField(max_length=32)),
                ('type', models.IntegerField(choices=[(1, 'URL'), (2, 'Content page'), (3, 'List/search shows'), (4, 'Schedule'), (5, 'List venues')])),
                ('url', models.URLField(blank=True, default='', max_length=32)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigator_options', to='core.Festival')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='navigator_options', to='core.ContentPage')),
            ],
            options={
                'ordering': ('festival', 'seqno', 'label'),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('site', 'festival', 'email')},
        ),
        migrations.AlterField(
            model_name='user',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.Festival'),
        ),
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='sites.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='navigatoroption',
            unique_together={('festival', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='contentpage',
            unique_together={('festival', 'name')},
        ),
    ]
