# Generated by Django 2.1.1 on 2018-09-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180922_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Festival'),
        ),
        migrations.AlterField(
            model_name='navigatoroption',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Festival'),
        ),
        migrations.AlterField(
            model_name='navigatoroption',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.ContentPage'),
        ),
    ]
