# Generated by Django 2.1.1 on 2018-09-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180922_1428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentpage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='festival',
        ),
        migrations.AlterUniqueTogether(
            name='navigatoroption',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='navigatoroption',
            name='festival',
        ),
        migrations.RemoveField(
            model_name='navigatoroption',
            name='page',
        ),
        migrations.DeleteModel(
            name='ContentPage',
        ),
        migrations.DeleteModel(
            name='NavigatorOption',
        ),
    ]
