# Generated by Django 2.1.3 on 2018-11-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180922_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='online_sales_close',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='online_sales_open',
            field=models.DateField(blank=True, null=True),
        ),
    ]
