# Generated by Django 2.1.3 on 2018-11-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181122_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_box_office',
            new_name='is_boxoffice',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_venue',
        ),
    ]
