# Generated by Django 2.1.5 on 2019-02-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181123_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
