# Generated by Django 4.0.5 on 2022-06-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_festival_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='button_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='festival',
            name='fringer_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='festival',
            name='fringer_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='festival',
            name='fringer_shows',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
