# Generated by Django 4.0.5 on 2022-06-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_festival_button_price_festival_fringer_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='fringer_payment',
        ),
    ]
