# Generated by Django 4.0.5 on 2022-06-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_festival_fringer_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='volunteer_comps',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
