# Generated by Django 4.0.5 on 2022-06-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_festival_volunteer_comps'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='boxoffice_close',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='boxoffice_open',
            field=models.DateField(blank=True, null=True),
        ),
    ]
