# Generated by Django 4.0.5 on 2023-02-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_festival_boxoffice_close_festival_boxoffice_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
