# Generated by Django 4.2 on 2023-09-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_user_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('festival', 'email')},
        ),
        migrations.DeleteModel(
            name='SiteInfo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='site',
        ),
    ]
