from django.urls import path

from . import views

app_name = "program"

urlpatterns = [
    path('shows', views.shows, name = 'shows'),
    path('show', views.shows, name = 'show_obsolete'),
    path('shows/<uuid:festival_uuid>', views.shows, name = 'shows'),
    path('show/<uuid:show_uuid>', views.show, name = 'show'),
    path('schedule', views.schedule, name = 'schedule'),
    path('schedule/<uuid:festival_id>', views.schedule, name = 'schedule'),
    path('schedule/pdf', views.schedule_pdf, name = 'schedule_pdf'),
    path('schedule/<uuid:festival_uuid>/pdf', views.schedule_pdf, name = 'schedule_pdf'),
    path('venues', views.venues, name = 'venues'),
    path('venues/<uuid:festival_uuid>', views.venues, name = 'venues'),
    path('venue/<uuid:venue_uuid>', views.venue, name = 'venue'),
    path('admin/genres', views.AdminGenreList.as_view(), name='admin_genres'),
    path('admin/genre/create', views.AdminGenreCreate.as_view(), name='admin_genre_create'),
    path('admin/genre/<uuid:slug>/update', views.AdminGenreUpdate.as_view(), name='admin_genre_update'),
    path('admin/genre/<uuid:slug>/delete', views.admin_genre_delete, name='admin_genre_delete'),
    path('admin/venues', views.AdminVenueList.as_view(), name='admin_venues'),
    path('admin/venue/create', views.AdminVenueCreate.as_view(), name='admin_venue_create'),
    path('admin/venue/<uuid:slug>/update', views.AdminVenueUpdate.as_view(), name='admin_venue_update'),
    path('admin/venue/<uuid:slug>/update/<tab>', views.AdminVenueUpdate.as_view(), name='admin_venue_update_tab'),
    path('admin/venue/<uuid:slug>/delete', views.admin_venue_delete, name='admin_venue_delete'),
    path('admin/venue/<uuid:venue_uuid>/contact/create', views.AdminVenueContactCreate.as_view(), name='admin_venue_contact_create'),
    path('admin/venue/<uuid:venue_uuid>/contact/<uuid:slug>/update', views.AdminVenueContactUpdate.as_view(), name='admin_venue_contact_update'),
    path('admin/venue/<uuid:venue_uuid>/contact/<uuid:slug>/delete', views.admin_venue_contact_delete, name='admin_venue_contact_delete'),
    path('admin/venue/<uuid:venue_uuid>/sponsor/create', views.AdminVenueSponsorCreate.as_view(), name='admin_venue_sponsor_create'),
    path('admin/venue/<uuid:venue_uuid>/sponsor/<uuid:slug>/update', views.AdminVenueSponsorUpdate.as_view(), name='admin_venue_sponsor_update'),
    path('admin/venue/<uuid:venue_uuid>/sponsor/<uuid:slug>/delete', views.admin_venue_sponsor_delete, name='admin_venue_sponsor_delete'),
    path('admin/companies', views.AdminCompanyList.as_view(), name='admin_companies'),
    path('admin/company/create', views.AdminCompanyCreate.as_view(), name='admin_company_create'),
    path('admin/company/<uuid:slug>/update', views.AdminCompanyUpdate.as_view(), name='admin_company_update'),
    path('admin/company/<uuid:slug>/update/<tab>', views.AdminCompanyUpdate.as_view(), name='admin_company_update_tab'),
    path('admin/company/<uuid:slug>/delete', views.admin_company_delete, name='admin_company_delete'),
    path('admin/company/<uuid:company_uuid>/contact/create', views.AdminCompanyContactCreate.as_view(), name='admin_company_contact_create'),
    path('admin/company/<uuid:company_uuid>/contact/<uuid:slug>/update', views.AdminCompanyContactUpdate.as_view(), name='admin_company_contact_update'),
    path('admin/company/<uuid:company_uuid>/contact/<uuid:slug>/delete', views.admin_company_contact_delete, name='admin_company_contact_delete'),
    path('admin/shows', views.AdminShowList.as_view(), name='admin_shows'),
    path('admin/show/create', views.AdminShowCreate.as_view(), name='admin_show_create'),
    path('admin/show/<uuid:slug>/update', views.AdminShowUpdate.as_view(), name='admin_show_update'),
    path('admin/show/<uuid:slug>/update/<tab>', views.AdminShowUpdate.as_view(), name='admin_show_update_tab'),
    path('admin/show/<uuid:slug>/delete', views.admin_show_delete, name='admin_show_delete'),
    path('admin/show/<uuid:show_uuid>/performance/create', views.AdminShowPerformanceCreate.as_view(), name='admin_show_performance_create'),
    path('admin/show/<uuid:show_uuid>/performance/<uuid:slug>/update', views.AdminShowPerformanceUpdate.as_view(), name='admin_show_performance_update'),
    path('admin/show/<uuid:show_uuid>/performance/<uuid:slug>/delete', views.admin_show_performance_delete, name='admin_show_performance_delete'),
    path('admin/show/<uuid:show_uuid>/review/create', views.AdminShowReviewCreate.as_view(), name='admin_show_review_create'),
    path('admin/show/<uuid:show_uuid>/review/<uuid:slug>/update', views.AdminShowReviewUpdate.as_view(), name='admin_show_review_update'),
    path('admin/show/<uuid:show_uuid>/review/<uuid:slug>/delete', views.admin_show_review_delete, name='admin_show_review_delete'),
    path('admin/show/<uuid:show_uuid>/image/create', views.AdminShowImageCreate.as_view(), name='admin_show_image_create'),
    path('admin/show/<uuid:show_uuid>/image/<uuid:slug>/update', views.AdminShowImageUpdate.as_view(), name='admin_show_image_update'),
    path('admin/show/<uuid:show_uuid>/image/<uuid:slug>/delete', views.admin_show_image_delete, name='admin_show_image_delete'),
]

