# Generated by Django 2.1.1 on 2018-09-17 19:29

from django.db import migrations, models
import django.db.models.deletion
import program.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, default='', upload_to=program.models.get_image_filename)),
                ('listing', models.TextField(blank=True, default='')),
                ('listing_short', models.TextField(blank=True, default='')),
                ('detail', models.TextField(blank=True, default='')),
                ('address1', models.CharField(blank=True, default='', max_length=64)),
                ('address2', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=32)),
                ('post_code', models.CharField(blank=True, default='', max_length=10)),
                ('telno', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=128)),
                ('website', models.URLField(blank=True, default='', max_length=128)),
                ('facebook', models.CharField(blank=True, default='', max_length=64)),
                ('twitter', models.CharField(blank=True, default='', max_length=64)),
                ('instagram', models.CharField(blank=True, default='', max_length=64)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='core.Festival')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('address1', models.CharField(blank=True, default='', max_length=64)),
                ('address2', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=32)),
                ('post_code', models.CharField(blank=True, default='', max_length=10)),
                ('telno', models.CharField(blank=True, default='', max_length=32)),
                ('mobile', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='program.Company')),
            ],
            options={
                'ordering': ('company', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='core.Festival')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, default='', upload_to=program.models.get_image_filename)),
                ('listing', models.TextField(blank=True, default='')),
                ('listing_short', models.TextField(blank=True, default='')),
                ('detail', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='', max_length=128)),
                ('facebook', models.CharField(blank=True, default='', max_length=64)),
                ('twitter', models.CharField(blank=True, default='', max_length=64)),
                ('instagram', models.CharField(blank=True, default='', max_length=64)),
                ('genre_text', models.CharField(blank=True, default='', max_length=64)),
                ('has_warnings', models.BooleanField(blank=True, default=False)),
                ('age_range', models.CharField(blank=True, default='', max_length=16)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(blank=True, default=False)),
                ('is_cancelled', models.BooleanField(blank=True, default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='program.Company')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='core.Festival')),
                ('genres', models.ManyToManyField(blank=True, related_name='shows', to='program.Genre')),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_for', to='program.Show')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShowImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, default='', upload_to=program.models.get_image_filename)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='program.Show')),
            ],
            options={
                'ordering': ('show', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShowPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='program.Show')),
            ],
            options={
                'ordering': ('show', 'date', 'time'),
            },
        ),
        migrations.CreateModel(
            name='ShowReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=128)),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], null=True)),
                ('body', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=128)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='program.Show')),
            ],
            options={
                'ordering': ('show', 'source'),
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, default='', upload_to=program.models.get_image_filename)),
                ('listing', models.TextField(blank=True, default='')),
                ('listing_short', models.TextField(blank=True, default='')),
                ('detail', models.TextField(blank=True, default='')),
                ('address1', models.CharField(blank=True, default='', max_length=64)),
                ('address2', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=32)),
                ('post_code', models.CharField(blank=True, default='', max_length=10)),
                ('telno', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=128)),
                ('website', models.URLField(blank=True, default='', max_length=128)),
                ('facebook', models.CharField(blank=True, default='', max_length=64)),
                ('twitter', models.CharField(blank=True, default='', max_length=64)),
                ('instagram', models.CharField(blank=True, default='', max_length=64)),
                ('is_ticketed', models.BooleanField(default=False)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('map_index', models.IntegerField(blank=True, default=0)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='core.Festival')),
            ],
            options={
                'ordering': ('festival', 'name'),
            },
        ),
        migrations.CreateModel(
            name='VenueContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('address1', models.CharField(blank=True, default='', max_length=64)),
                ('address2', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=32)),
                ('post_code', models.CharField(blank=True, default='', max_length=10)),
                ('telno', models.CharField(blank=True, default='', max_length=32)),
                ('mobile', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=64)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='program.Venue')),
            ],
            options={
                'ordering': ('venue', 'name'),
            },
        ),
        migrations.CreateModel(
            name='VenueSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, default='', upload_to=program.models.get_image_filename)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('background', models.CharField(blank=True, default='', max_length=16)),
                ('message', models.CharField(blank=True, default='', max_length=32)),
                ('website', models.URLField(blank=True, default='', max_length=128)),
                ('facebook', models.CharField(blank=True, default='', max_length=64)),
                ('twitter', models.CharField(blank=True, default='', max_length=64)),
                ('instagram', models.CharField(blank=True, default='', max_length=64)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='program.Venue')),
            ],
            options={
                'ordering': ('venue', 'name'),
            },
        ),
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='program.Venue'),
        ),
        migrations.AlterUniqueTogether(
            name='venuesponsor',
            unique_together={('venue', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='venuecontact',
            unique_together={('venue', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('festival', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='showperformance',
            unique_together={('show', 'date', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='showimage',
            unique_together={('show', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('festival', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('festival', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='companycontact',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('festival', 'name')},
        ),
    ]
