# Generated by Django 2.1.5 on 2019-02-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuesponsor',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='venuesponsor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='venuesponsor',
            name='telno',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
