# Generated by Django 4.2 on 2023-09-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    init_performance_venue_SQL = ' '.join([
        'update program_showperformance psp',
        'set venue_id = ps.venue_id',
        'from program_show ps',
        'where ps.id = psp.show_id',
    ])

    operations = [
        migrations.AddField(
            model_name='showperformance',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='program.venue'),
        ),
        migrations.RunSQL(init_performance_venue_SQL),
        migrations.AlterField(
            model_name='showperformance',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='program.venue'),
        ),
    ]
