# Generated by Django 2.2 on 2019-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20190213_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='showperformance',
            name='audience',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
