# Generated by Django 4.2 on 2023-09-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_remove_show_venue'),
    ]

    init_show_is_ticketed_SQL = ' '.join([
        'update program_show ps',
        'set is_ticketed = pv.is_ticketed',
        'from program_showperformance psp',
        'join program_venue pv on pv.id = psp.venue_id',
        'where psp.show_id = ps.id',
    ])

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_ticketed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.RunSQL(init_show_is_ticketed_SQL),
    ]
