# Generated by Django 2.2.1 on 2019-06-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_showperformance_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='showperformance',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
