# Generated by Django 4.0.5 on 2023-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_showperformance_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='warnings',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
