# Generated by Django 4.2 on 2023-09-26 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, default='', max_length=32)),
                ('information', models.TextField(blank=True, default='')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.festival')),
            ],
            options={
                'ordering': ('festival', 'description'),
                'unique_together': {('festival', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, default='', max_length=32)),
                ('comps_per_shift', models.FloatField(default=0)),
                ('information', models.TextField(blank=True, default='')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.festival')),
            ],
            options={
                'ordering': ('festival', 'description'),
                'unique_together': {('festival', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='volunteer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_dbs', models.BooleanField(default=False)),
                ('roles', models.ManyToManyField(blank=True, related_name='volunteers', to='volunteers.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('needs_dbs', models.BooleanField(default=False)),
                ('volunteer_can_accept', models.BooleanField(blank=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='volunteers.location')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='volunteers.role')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='volunteers.volunteer')),
            ],
            options={
                'ordering': ('location', 'date', 'start_time', 'role'),
                'unique_together': {('location', 'date', 'start_time', 'role')},
            },
        ),
    ]
