# Generated by Django 2.1.4 on 2019-02-03 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        ('core', '0014_auto_20181123_1729'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.Festival')),
            ],
            options={
                'ordering': ('festival', 'description'),
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='volunteers.Role')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='program.Venue')),
            ],
            options={
                'ordering': ('venue', 'date', 'start_time', 'role'),
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='volunteers', to='volunteers.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='volunteers.Volunteer'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('venue', 'date', 'start_time', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('festival', 'description')},
        ),
    ]
