# Generated by Django 4.2 on 2023-10-29 16:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, default='', max_length=32)),
                ('needs_dbs', models.BooleanField(default=False)),
                ('volunteer_can_accept', models.BooleanField(blank=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='core.festival')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='volunteers.role')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='volunteers.volunteer')),
            ],
            options={
                'ordering': ('festival', 'description'),
                'unique_together': {('festival', 'description')},
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='commitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='volunteers.commitment'),
        ),
    ]
