# Generated by Django 2.1.4 on 2019-02-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, default='', max_length=32),
        ),
    ]
