# Generated by Django 4.2 on 2023-09-25 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('create table xxx_shift (like volunteers_shift)'),
        migrations.RunSQL('insert into xxx_shift select * from volunteers_shift'),
        migrations.RunSQL('update xxx_shift xx set volunteer_id = vv.user_id from volunteers_volunteer vv where vv.id = xx.volunteer_id'),
        migrations.RunSQL('create table xxx_volunteer_roles (like volunteers_volunteer_roles)'),
        migrations.RunSQL('insert into xxx_volunteer_roles select * from volunteers_volunteer_roles'),
        migrations.RunSQL('update xxx_volunteer_roles xx set volunteer_id = vv.user_id from volunteers_volunteer vv where vv.id = xx.volunteer_id'),

        migrations.RunSQL('delete from volunteers_shift'),
        migrations.RunSQL('delete from volunteers_volunteer_roles'),

        migrations.RunSQL('alter table volunteers_shift drop constraint volunteers_shift_volunteer_id_22e0e075_fk_volunteer_volunteer_i'),
        migrations.RunSQL('alter table volunteers_volunteer_roles drop constraint volunteers_volunteer__volunteer_id_b1bbf70a_fk_volunteer'),
        migrations.RunSQL('alter table volunteers_volunteer drop constraint volunteers_volunteer_pkey'),
        migrations.RunSQL('alter table volunteers_volunteer drop constraint volunteers_volunteer_user_id_6618f64a_fk_core_user_id'),
        migrations.RunSQL('alter table volunteers_volunteer drop column id'),

        migrations.RunSQL('alter table volunteers_volunteer add primary key (user_id)'),
        migrations.RunSQL('alter table volunteers_volunteer add foreign key (user_id) references core_user (id)'),
        migrations.RunSQL('alter table volunteers_shift add foreign key (volunteer_id) references volunteers_volunteer (user_id)'),
        migrations.RunSQL('alter table volunteers_volunteer_roles add foreign key (volunteer_id) references volunteers_volunteer (user_id)'),

        migrations.RunSQL('insert into volunteers_shift select * from xxx_shift'),
        migrations.RunSQL('insert into volunteers_volunteer_roles select * from xxx_volunteer_roles'),
    ]
