# Generated by Django 2.1.5 on 2019-02-10 17:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181123_1729'),
        ('volunteers', '0002_auto_20190203_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, default='', max_length=32)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.Festival')),
            ],
            options={
                'ordering': ('festival', 'description'),
            },
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ('location', 'date', 'start_time', 'role')},
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='shift',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='volunteers.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('location', 'date', 'start_time', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('festival', 'description')},
        ),
    ]
