# Generated by Django 5.0.14 on 2026-03-14 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_add_commitments'),
        ('core', '0005_merge_volunteer_into_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_commitments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL('update volunteers_commitment set user_id = volunteer_id where volunteer_id is not null', reverse_sql=''),
        migrations.AddField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL('update volunteers_shift set user_id = volunteer_id where volunteer_id is not null', reverse_sql=''),
        migrations.RemoveField(
            model_name='shift',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
