# Generated by Django 2.1.5 on 2019-02-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_auto_20190210_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='venue',
        ),
        migrations.AlterField(
            model_name='shift',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='volunteers.Location'),
        ),
    ]
