# Generated by Django 2.1.5 on 2019-02-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_auto_20190210_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='role',
            name='information',
            field=models.TextField(blank=True, default=''),
        ),
    ]
