# Generated by Django 2.2 on 2019-05-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_shift_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='volunteer_can_accept',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
