# Generated by Django 4.0.5 on 2022-06-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_remove_shift_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='needs_dbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_dbs',
            field=models.BooleanField(default=False),
        ),
    ]
