# Generated by Django 4.0.5 on 2022-06-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_shift_needs_dbs_volunteer_is_dbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='comps_per_shift',
            field=models.FloatField(default=0),
        ),
    ]
