# Generated by Django 2.1.3 on 2018-11-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180922_1454'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='core.Festival'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.Festival'),
            preserve_default=False,
        ),
    ]
