# Generated by Django 4.2 on 2023-09-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    add_efringer_tickettype_SQL = ' '.join([
        "insert",
        "into tickets_tickettype",
        "(uuid, created, updated, festival_id, name, seqno, price, payment, is_online, is_admin, rules)",
        "select	uuid_generate_v4(), clock_timestamp(), clock_timestamp(), cf.id, 'eFringer', 5, 0, case cf.fringer_shows when 0 then 0 else cf.fringer_price/cf.fringer_shows end, false, false, ''",
        "from core_festival cf",
    ])

    add_volunteer_tickettype_SQL = ' '.join([
        "insert",
        "into tickets_tickettype",
        "(uuid, created, updated, festival_id, name, seqno, price, payment, is_online, is_admin, rules)",
        "select	uuid_generate_v4(), clock_timestamp(), clock_timestamp(), cf.id, 'Volunteer', 6, 0, 0, false, false, ''",
        "from core_festival cf",
    ])

    operations = [
        migrations.RunSQL(add_efringer_tickettype_SQL),
        migrations.RunSQL(add_volunteer_tickettype_SQL),
    ]
