# Generated by Django 4.2 on 2024-03-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_add_sale_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='buttons',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
