# Generated by Django 4.2 on 2023-09-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_add_tickettypes'),
    ]

    init_ticket_type_SQL = ' '.join([
        "update tickets_ticket tt",
        "set type_id = ttt.id",
        "from program_showperformance psp",
        "join program_show ps on ps.id = psp.show_id",
        "join tickets_tickettype ttt on ttt.festival_id = ps.festival_id",
        "where psp.id = tt.performance_id",
        "and ttt.name = tt.description"
    ])

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype'),
        ),
        migrations.RunSQL(init_ticket_type_SQL),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype')
        ),
    ]
