# Generated by Django 2.1.3 on 2018-11-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('tickets', '0003_auto_20181122_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='program.Venue'),
        ),
    ]
