# Generated by Django 4.2 on 2024-03-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_add_online_buttons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction_ID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
