# Generated by Django 4.2 on 2023-09-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_add_ticket_type'),
    ]

    init_tickettype_is_venue_SQL = ' '.join([
        "update tickets_tickettype set is_venue = true where name in ('Full', 'Concession', 'Fringer', 'Reviewer')",
    ])

    init_tickettype_is_boxoffice_SQL = ' '.join([
        "update tickets_tickettype set is_boxoffice = true where name in ('Full', 'Concession', 'Fringer')",
    ])

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='is_boxoffice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='is_venue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype'),
        ),
        migrations.RunSQL(init_tickettype_is_venue_SQL),
        migrations.RunSQL(init_tickettype_is_boxoffice_SQL),
    ]
