# Generated by Django 2.2 on 2019-04-27 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20190213_1531'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_sale_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('buttons', models.IntegerField(blank=True, default=0)),
                ('fringers', models.IntegerField(blank=True, default=0)),
                ('boxoffice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkpoints', to='tickets.BoxOffice')),
                ('close_performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_checkpoint', to='program.ShowPerformance')),
                ('open_performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_checkpoint', to='program.ShowPerformance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkpoints', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkpoints', to='program.Venue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
