# Generated by Django 4.2 on 2023-09-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_cleanup'),
    ]

    add_paper_fringertype_SQL = ' '.join([
        "insert",
        "into tickets_fringertype",
        "(uuid, created, updated, festival_id, name, shows, price, is_online, rules, payment)",
        "select uuid_generate_v4(), clock_timestamp(), clock_timestamp(), cf.id, 'Paper', cf.fringer_shows, cf.fringer_price, false, '', cf.fringer_price/cf.fringer_shows",
        "from core_festival cf",
        "where cf.fringer_shows > 0"
    ])

    operations = [
        migrations.RunSQL(add_paper_fringertype_SQL),
    ]
