# Generated by Django 4.2 on 2024-03-20 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0001_initial'),
        ('tickets', '0004_increase_transactionID_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgesIssued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('badges', models.IntegerField()),
                ('boxoffice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='badges_issued', to='tickets.boxoffice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='badges_issued', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='badges_issued', to='program.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
