# Generated by Django 5.0.9 on 2024-11-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_add_tickets_badgesissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='description',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
