# Generated by Django 4.2 on 2023-09-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_add_fringertypes'),
    ]

    init_efringer_type_SQL = ' '.join([
        "update tickets_fringer tf",
        "set type_id = tft.id",
        "from core_user cu",
        "join tickets_fringertype tft on tft.festival_id = cu.festival_id and tft.is_online = true",
        "where cu.id = tf.user_id",
    ])

    init_paper_fringer_type_SQL = ' '.join([
        "update tickets_fringer tf",
        "set type_id = tft.id",
        "from tickets_sale ts",
        "join tickets_fringertype tft on tft.festival_id = ts.festival_id and tft.is_online = false",
        "where ts.id = tf.sale_id",
        "and tf.user_id is null",
    ])

    operations = [
        migrations.AddField(
            model_name='fringer',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fringers', to='tickets.fringertype'),
        ),
        migrations.RunSQL(init_efringer_type_SQL),
        migrations.RunSQL(init_paper_fringer_type_SQL),
        migrations.AlterField(
            model_name='fringer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fringers', to='tickets.fringertype'),
        ),
    ]
