# Generated by Django 2.2 on 2019-04-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='buttons',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='fringers',
            field=models.IntegerField(),
        ),
    ]
