# Generated by Django 2.2 on 2019-04-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190428_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='close_performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='close_checkpoint', to='program.ShowPerformance'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='open_performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='open_checkpoint', to='program.ShowPerformance'),
        ),
    ]
