# Generated by Django 4.2 on 2023-09-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_add_fringer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fringer',
            name='shows',
        ),
        migrations.RemoveField(
            model_name='fringer',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='fringer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fringer',
            name='payment',
        ),
    ]
