# Generated by Django 5.0.9 on 2025-06-22 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('tickets', '0006_add_previous_festival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buckets', to='program.show'),
        ),
        migrations.CreateModel(
            name='PAYWCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=32)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PAYW_cards', to='program.company')),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PAYW_cards', to='program.showperformance')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PAYW_cards', to='program.show')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
