# Generated by Django 4.2 on 2023-09-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_fringer_cleanup'),
    ]

    operations = [
        migrations.RunSQL("delete from tickets_fringertype where festival_id = (select id from core_festival where name = 'TF2021')"),
        migrations.RunSQL("delete from tickets_tickettype where festival_id = (select id from core_festival where name = 'TF2021')"),
    ]
