# Generated by Django 5.0.9 on 2025-06-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_add_PAYWCard'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='cards',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PAYWCard',
        ),
    ]
