# Generated by Django 4.2 on 2023-09-23 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_cleanup_2021'),
    ]

    init_fringer_ticket_type_SQL = ' '.join([
        "update tickets_fringertype tft",
        "set ticket_type_id = (select id from tickets_tickettype where festival_id = tft.festival_id and name = 'Fringer')",
        "where tft.is_online = false",
    ])

    init_efringer_ticket_type_SQL = ' '.join([
        "update tickets_fringertype tft",
        "set ticket_type_id = (select id from tickets_tickettype where festival_id = tft.festival_id and name = 'eFringer')",
        "where tft.is_online = true",
    ])

    operations = [
        migrations.AddField(
            model_name='fringertype',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fringer_types', to='tickets.tickettype'),
        ),
        migrations.RunSQL(init_fringer_ticket_type_SQL),
        migrations.RunSQL(init_efringer_ticket_type_SQL),
        migrations.AlterField(
            model_name='fringertype',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fringer_types', to='tickets.tickettype'),
        ),
    ]
