# Generated by Django 2.2.1 on 2019-06-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_remove_shift_ticket'),
        ('tickets', '0008_auto_20190428_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='volunteers.Shift'),
        ),
    ]
