# Generated by Django 5.0.9 on 2025-06-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_Add_PAYW_cards_to_buckets'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='audience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
