# Generated by Django 2.2.1 on 2019-06-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='shift',
        ),
    ]
