# Generated by Django 4.2 on 2023-09-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_add_fringer_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fringertype',
            name='payment',
        ),
    ]
