# Generated by Django 3.2.3 on 2021-06-14 07:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_festival_banner'),
        ('tickets', '0010_remove_ticket_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='core.festival')),
            ],
            options={
                'ordering': ('festival', 'created'),
            },
        ),
    ]
