# Generated by Django 4.0.5 on 2022-06-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='token_issued',
            field=models.BooleanField(default=False),
        ),
    ]
