# Generated by Django 4.0.5 on 2022-06-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_token_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stripe_pi',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
