# Generated by Django 4.0.5 on 2022-06-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_sale_stripe_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
