# Generated by Django 4.0.5 on 2023-02-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_show_warnings'),
        ('tickets', '0014_sale_cancelled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fringer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='close_performance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='close_checkpoint', to='program.showperformance'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='open_performance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='open_checkpoint', to='program.showperformance'),
        ),
    ]
