# Generated by Django 4.2 on 2023-05-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_fringer_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='stripe_fee',
            new_name='transaction_fee',
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Cash'), (2, 'Stripe'), (3, 'SquareUp')], null=True),
        ),
        migrations.RunSQL('update tickets_sale set transaction_type = 1 where transaction_fee = 0'),
        migrations.RunSQL('update tickets_sale set transaction_type = 2 where transaction_fee > 0'),
    ]
