# Generated by Django 4.2 on 2023-06-16 15:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_show_warnings'),
        ('tickets', '0016_rename_stripe_fee_sale_transaction_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='donation',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='PayAsYouWill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_as_you_will', to='tickets.sale')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_as_you_will', to='program.show')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
