# Generated by Django 4.2 on 2023-06-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_show_warnings'),
        ('tickets', '0017_pay_as_you_will'),
    ]

    operations = [
        migrations.AddField(
            model_name='payasyouwill',
            name='fringer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PAYW_donations', to='tickets.fringer'),
        ),
        migrations.AlterField(
            model_name='payasyouwill',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PAYW_donations', to='tickets.sale'),
        ),
        migrations.AlterField(
            model_name='payasyouwill',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PAYW_donations', to='program.show'),
        ),
    ]
