# Generated by Django 4.2 on 2023-07-01 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_show_warnings'),
        ('tickets', '0018_eFringer_PAYW'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=32)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fringers', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buckets', to='program.company')),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buckets', to='program.showperformance')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buckets', to='program.show')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
